// errors
exports.ERR_OK = 0;
exports.ERR_CONNECT_FAIL_API = 1000;
exports.ERR_INVALID_PARAMETER = 1001;
exports.ERR_ALREADY_LOGIN = 1002;
exports.ERR_UNKNOWN_COMMAND = 1003;
exports.ERR_INTERVIEW_NOT_PROGRESS = 1004;
exports.ERR_NO_INTERVIEW = 1005;