#!/bin/bash
#
#	/etc/rc.d/init.d/recording
#
# Starts the recording daemon
#
# chkconfig: 345 44 56
# description: execute batch service for recording
# processname: recording

# Source function library.
. /etc/rc.d/init.d/functions

[ -x /usr/sbin/recording.sh ] || exit 0

RETVAL=0

#
# See how we were called.
#

start() {
	# Check if it is already running
	if [ ! -f /var/lock/subsys/recording ]; then
	    echo -n $"Starting recording batch daemon: "
	    daemon /usr/sbin/recording.sh
	    RETVAL=$?
	    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/recording
	    echo
	fi
	return $RETVAL
}

stop() {
	echo -n $"Stopping recording batch daemon: "
	killproc /usr/sbin/recording.sh
	RETVAL=$?
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/recording
	echo
    return $RETVAL
}


restart() {
	stop
	start
}	

reload() {
	trap "" SIGHUP
	killall -HUP recording.sh
}	

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
reload)
	reload
	;;
restart)
	restart
	;;
condrestart)
	if [ -f /var/lock/subsys/recording ]; then
	    restart
	fi
	;;
status)
	status recording.sh
	;;
*)
	echo $"Usage: $0 {start|stop|status|restart|condrestart|reload}"
	exit 1
esac

exit $RETVAL
